### ISSUE TITLE
LPRun tries to read LINQPad.Runtime.dll

### ISSUE THREAD

**Issue by romfir** [i2van/CsvLINQPadDriver#11]
When I try to run tests of my Context Driver using `LPRun` (Version="7.8.5") I get `Could not load file or assembly 'LINQPad.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=21353812cd2a2db5'` error, after manually copying `LINQPad.Runtime.dll` from `\bin\Debug\net7.0-windows\LPRun\Bin` to `\bin\Debug\net7.0-windows` it starts to work (I tried running it under both NUnit and XUnit)

workaround (inside tests .csproj)
```csproj
<Target Name="TestTarget" AfterTargets="Build">
	<Copy SourceFiles="$(OutputPath)\LPRun\Bin\LINQPad.Runtime.dll" DestinationFiles="$(OutputPath)\LINQPad.Runtime.dll" UseHardlinksIfPossible="true"/>
</Target>
```

My config:

```csharp
Driver.InstallWithDepsJson(
    "OpenApiLINQPadDriver",
    "OpenApiLINQPadDriver.dll",
    "Tests"
);
```

with folder structure:
* OpenApiLINQPadDriver  (driver)
  * Tests
    * OpenApiLINQPadDriverTests

full source code: https://github.com/romfir/OpenApiLINQPadDriver/tree/tests

side note:
I know you did point out in the readme that the driver must not be manually installed via Nuget/Folder inside LINQPad but maybe it would be a good idea to manually check for existance of `%localappdata%\LINQPad\NuGet.Drivers\<driverName>` and  `%localappdata%\LINQPad\Drivers\DataContext\NetCore\<driverName>` and throwing some exception :) If thats ok with you I can implement it

**Comment by i2van** [comment]
Dependency to `LINQPad.Runtime.dll` `IConnectionInfo` interface was introduced in test [here](https://github.com/romfir/OpenApiLINQPadDriver/blob/222b2edccca8fe56189662929a71144308f1bd9a/Tests/OpenApiLINQPadDriverTests/UnitTest1.cs#L25). Interface extraction for `OpenApiContextDriverProperties` and setting up the **all non-default** values solves the issue:

```csharp
var driverProperties = Mock.Of<IOpenApiContextDriverProperties>(props =>
    props.OpenApiDocumentUri == $"{_apiFixture.ApiUrl}swagger/v1/swagger.json" &&
    props.ApiUri == _apiFixture.ApiUrl &&
    props.EndpointGrouping == EndpointGrouping.MultipleClientsFromFirstTagAndOperationName &&
    props.JsonLibrary == JsonLibrary.SystemTextJson);
```

I also had to change `https` to `http` [here](https://github.com/romfir/OpenApiLINQPadDriver/blob/222b2edccca8fe56189662929a71144308f1bd9a/Tests/OpenApiLINQPadDriverTests/UnitTest1.cs#L92).

Please find files changed attached in zip, just copy its content to `tests` branch (save your work first of course).

[OpenApiLINQPadDriver.zip](https://github.com/i2van/CsvLINQPadDriver/files/12592065/OpenApiLINQPadDriver.zip)

Regarding check for driver installed - it is a good idea. I'll consider it.

I'll also update documentation accordingly.

Thank you!

**Comment by i2van** [comment]
@romfir NuGet check [has been added](https://github.com/i2van/CsvLINQPadDriver/commit/9d713c8030877ba0338ab1cc5a7214762550ed8a). Scheduled for next LINQPad release.

**Comment by romfir** [comment]
Great! I think you should also check `\LINQPad\Drivers\DataContext\NetCore` folder for any manual instalations possibly via other method :)

**Comment by i2van** [comment]
> Great! I think you should also check `\LINQPad\Drivers\DataContext\NetCore` folder for any manual instalations possibly via other method :)

No need. LPRun does not priorities it over local one.

**Comment by i2van** [comment]
Reopened to keep track.

**Comment by i2van** [comment]
[Implemented](https://github.com/i2van/CsvLINQPadDriver/blob/b30490c43fc1d2efca380d1284226a4d87d81c23/Src/LPRun/Driver.cs#L142) in [LPRun 7.8.7-beta1](https://www.nuget.org/packages/LPRun/7.8.7-beta1)

* LPRun 7.8.6
* Added Driver.EnsureNotInstalledViaNuGet method.
* Added LinqScript.FromFile method.
* Added LinqScript.FromScript method.
