### ISSUE TITLE
LPRun package only contains files for netstandard2.1

### ISSUE THREAD

**Issue by romfir** [i2van/CsvLINQPadDriver#12]
when I was building this solution manually the package contained all other frameworks `net5.0;net6.0;net7.0`
additionaly LINQPad files are inside `contentFiles\any\netstandard2.1\`, they probably should be inside `contentFiles\any\any\`.
<img width="262" alt="image" src="https://github.com/i2van/CsvLINQPadDriver/assets/33402460/81f1edbd-a82b-4d8d-90b9-c1b26ee4be0a">

**Comment by i2van** [comment]
Fixed in [LPRun-7.8.6-alpha4](https://www.nuget.org/packages/LPRun/7.8.6-alpha4)
