### ISSUE TITLE
German Characters

### ISSUE THREAD

**Issue by llewelynrex** [i2van/CsvLINQPadDriver#7]
When querying some CSV-Files I am having the problem that the characters ä, ö, ü, Ä, Ö, Ü and ß are displayed as ?. Is there a way to configure the driver to read the file with a specific encoding (like ANSI or Windows-1252)? I only see the option of a "Fallback encoding", but this unfortunately does not display the data correctly.
Example:
![image](https://user-images.githubusercontent.com/9720471/126353355-ac8c9489-8808-4231-961b-77c268d5bb44.png)

This is supposed to say Schichtdickenprüfgerät.

**Comment by i2van** [comment]
I tried UTF/Unicode files with `Schichtdickenprüfgerät` and it works fine.

However is file is saved in [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) encoding (which is probably the case) and you have corresponding locale set up then uncheck `Auto-detect file encodings` and try the following `Fallback encoding`s:

* `ASCII`
* `System code page`
* `User code page`

Could you please send me CSV file (or part of it in question) for further investigation?

**Comment by i2van** [comment]
I managed to make it work with Windows-1252 encoding ([German.zip](https://github.com/i2van/CsvLINQPadDriver/files/6853073/German.zip)) and unchecked `Auto-detect file encodings` and `Fallback encoding` set to `User code page` (I have Cyrillic locale).

![image](https://user-images.githubusercontent.com/5464660/126437031-8cd39411-839d-47ad-95e0-3971cb7f8c90.png)

![image](https://user-images.githubusercontent.com/5464660/126436581-f33ae515-9c85-4a48-ab58-af1ac6a69b51.png)

**Comment by i2van** [comment]
Fixed in [6.15.0](https://github.com/i2van/CsvLINQPadDriver/releases/tag/6.15.0)

**Comment by llewelynrex** [comment]
Wow! That was fast! It works now. Thank you.
